class CreatePointSystems < ActiveRecord::Migration
  def change
    create_table :point_systems do |t|
      t.integer :season_id
      t.integer :pts_1
      t.integer :pts_2
      t.integer :pts_3
      t.integer :pts_4
      t.integer :pts_5
      t.integer :pts_6
      t.integer :pts_7
      t.integer :pts_8
      t.integer :pts_9
      t.integer :pts_10
      t.integer :pts_11
      t.integer :pts_12
      t.integer :pts_13
      t.integer :pts_14
      t.integer :pts_15
      t.integer :pts_16
      t.integer :pts_17
      t.integer :pts_18
      t.integer :pts_19
      t.integer :pts_20
      t.integer :pts_21
      t.integer :pts_22
      t.integer :pts_23
      t.integer :pts_24
      t.integer :pts_25
      t.integer :pts_26
      t.integer :pts_27
      t.integer :pts_28
      t.integer :pts_29
      t.integer :pts_30
      t.integer :pts_31
      t.integer :pts_32
      t.integer :pts_33
      t.integer :pts_34
      t.integer :pts_35
      t.integer :pts_36
      t.integer :pts_37
      t.integer :pts_38
      t.integer :pts_39
      t.integer :pts_40
      t.integer :pts_41
      t.integer :pts_42
      t.integer :pts_43
      t.integer :pts_44
      t.integer :pts_45
      t.integer :pts_46
      t.integer :pts_47
      t.integer :pts_48
      t.integer :pts_49
      t.integer :pts_50
      t.integer :pts_51
      t.integer :pts_52
      t.integer :pts_53
      t.integer :pts_54
      t.integer :pts_55
      t.integer :pts_56
      t.integer :pts_57
      t.integer :pts_58
      t.integer :pts_59
      t.integer :pts_60
      t.integer :pts_61
      t.integer :pts_62
      t.integer :pts_63
      t.integer :pts_64
      t.integer :pts_65
      t.integer :pts_66
      t.integer :pts_67
      t.integer :pts_68
      t.integer :pts_69
      t.integer :pts_70
      t.integer :pts_71
      t.integer :pts_72
      t.integer :pts_73
      t.integer :pts_74
      t.integer :pts_75
      t.integer :pts_76
      t.integer :pts_77
      t.integer :pts_78
      t.integer :pts_79
      t.integer :pts_80
      t.integer :pts_81
      t.integer :pts_82
      t.integer :pts_83
      t.integer :pts_84
      t.integer :pts_85
      t.integer :pts_86
      t.integer :pts_87
      t.integer :pts_88
      t.integer :pts_89
      t.integer :pts_90
      t.integer :pts_91
      t.integer :pts_92
      t.integer :pts_93
      t.integer :pts_94
      t.integer :pts_95
      t.integer :pts_96
      t.integer :pts_97
      t.integer :pts_98
      t.integer :pts_99
      t.integer :pts_100

      t.timestamps
    end
  end
end
